# Generated by Django 4.1.7 on 2023-04-12 10:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context_dia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
    ]
